spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
logging:
  level:
    com.com.example.maps_apo: debug
    org.hibernate.type.descriptor.sql: trace
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
